// <auto-generated />
using System;
using LeilaoCarro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeilaoCarro.Migrations
{
    [DbContext(typeof(LeilaoContext))]
    [Migration("20240823192254_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("LeilaoCarro.Models.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short?>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraCadastrado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataHoraLeiloado")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdLance")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LanceInicial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdLance");

                    b.ToTable("Carro");
                });

            modelBuilder.Entity("LeilaoCarro.Models.Estado", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("LeilaoCarro.Models.Lance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraLance")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCarro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCarro");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Lance");
                });

            modelBuilder.Entity("LeilaoCarro.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("LeilaoCarro.Models.UsuarioEndereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Complemento")
                        .HasColumnType("TEXT");

                    b.Property<byte>("IdEstado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdUsuario");

                    b.ToTable("UsuarioEndereco");
                });

            modelBuilder.Entity("LeilaoCarro.Models.Carro", b =>
                {
                    b.HasOne("LeilaoCarro.Models.Lance", "Lance")
                        .WithMany("Carros")
                        .HasForeignKey("IdLance");

                    b.Navigation("Lance");
                });

            modelBuilder.Entity("LeilaoCarro.Models.Lance", b =>
                {
                    b.HasOne("LeilaoCarro.Models.Carro", "Carro")
                        .WithMany("Lances")
                        .HasForeignKey("IdCarro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeilaoCarro.Models.Usuario", "Usuario")
                        .WithMany("Lances")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LeilaoCarro.Models.UsuarioEndereco", b =>
                {
                    b.HasOne("LeilaoCarro.Models.Estado", "Estado")
                        .WithMany("UsuarioEndereco")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeilaoCarro.Models.Usuario", "Usuario")
                        .WithMany("UsuarioEnderecos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LeilaoCarro.Models.Carro", b =>
                {
                    b.Navigation("Lances");
                });

            modelBuilder.Entity("LeilaoCarro.Models.Estado", b =>
                {
                    b.Navigation("UsuarioEndereco");
                });

            modelBuilder.Entity("LeilaoCarro.Models.Lance", b =>
                {
                    b.Navigation("Carros");
                });

            modelBuilder.Entity("LeilaoCarro.Models.Usuario", b =>
                {
                    b.Navigation("Lances");

                    b.Navigation("UsuarioEnderecos");
                });
#pragma warning restore 612, 618
        }
    }
}
